version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.0.0
    working_directory: ~/project/
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{checksum "package.json"}}
          paths:
            - ./node_modules
      - run:
          name: make artifacts directories
          command: |
            mkdir artifacts
            mkdir artifacts/test-reports
      - run:
          name: Executing unit test cases
          command: npm test
      - store_artifacts:
          path: artifacts
      - store_test_results:
          path: artifacts/test-reports
      - sonarcloud/scan
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.0
workflows:
  main:
    jobs:
      - build:
          context: SonarCloud